version: "3.9"

services:
  mongo:
    image: mongo
    container_name: devshort-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  backend:
    build:
      context: ..
      dockerfile: devops/backend.Dockerfile
    container_name: devshort-backend
    ports:
      - "3001:3001"
    env_file:
      - ../backend/.env
    environment:
      - MONGO_URI=mongodb://mongo:27017/devshort
      - PORT=3001
    depends_on:
      - mongo

  frontend:
    build:
      context: ..
      dockerfile: devops/frontend.Dockerfile
    container_name: devshort-frontend
    ports:
      - "3000:3000"
    env_file:
      - ../frontend/.env
    environment:
      - REACT_APP_API_URL=http://backend:3001
    depends_on:
      - backend

volumes:
  mongo-data:
